name: Update Bin
on: 
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main
    - name: Download Core
      run: |
        download_file_name=$(wget -O - "https://api.github.com/repos/Dreamacro/clash/releases/tags/premium" 2> /dev/null | jq ".assets[].name" | grep -m 1 "linux-armv8" | xargs)
        if [[ -z "$download_file_name" ]]; then
          echo -n "Unable to list clash files."
          exit 1
        fi
        echo "Filename: $download_file_name"
        ver="${download_file_name%.*}"
        cd /tmp
        mkdir -p $ver
        wget "https://github.com/Dreamacro/clash/releases/download/premium/$download_file_name" -O /tmp/$ver/clash.gz
        echo "$ver" > clash_binary_lastest.txt
    - name: GZIP
      run: |
        npm install gzip-cli
        gzip -d -f /tmp/$ver/clash.gz
        md5sum /tmp/$ver/clash > /tmp/$ver/md5sum.txt
        cp /tmp/* ./
        rm -fr /tmp
    - name: Commit and push
      run: |
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add . && git commit -m "Update Core to ${ver}" || exit 0
        git push
