name: Update Bin
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true
    - name: Download Core
      run: |
        download_file_name=$(wget -O - "https://api.github.com/repos/Dreamacro/clash/releases/tags/premium" 2> /dev/null | jq ".assets[].name" | grep -m 1 "linux-arm64" | xargs)
        if [[ -z "$download_file_name" ]]; then
          echo -n "Unable to list clash files."
          exit 1
        fi
        echo "Filename: $download_file_name"
        ver="${download_file_name%.*}"
        mkdir -p /tmp/core/$ver
        mkdir -p core
        wget "https://github.com/Dreamacro/clash/releases/download/premium/$download_file_name" -q --show-progress -O /tmp/core/$ver/clashfull.gz
        echo "$ver" > /tmp/core/clash_binary_lastest.txt
        gzip -d -f /tmp/core/$ver/clashfull.gz
        upx -fq9 -o clash /tmp/core/$ver/clashfull
        rm -f clashfull
        md5sum /tmp/core/$ver/clash |awk '{print $1}' | tr a-z A-Z > /tmp/core/$ver/md5sum.txt
        cp -rfa /tmp/core/* core
        rm -fr /tmp/core
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add . && git commit -m "Update Core to ${ver}" || exit 0
        git push
    - name: Delete old versions
      if: github.ref == 'refs/heads/main'
      run: |
        git fetch --prune --unshallow
        git tag -l | grep "Update Core to" | sort -V | head -n -3 | xargs git tag -d
        git push --force --tags origin master
